/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg5009cem_assignment;

import javax.swing.JButton;

/**
 *
 * @author sjjde
 */
public class ApartmentManagerInterface extends javax.swing.JFrame {

    /**
     * Creates new form ApartmentManagerInterface
     */
    public ApartmentManagerInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monthlyTrack_dialog = new javax.swing.JDialog();
        generateRpt_btn = new javax.swing.JButton();
        trackedDetails_btn = new javax.swing.JButton();
        appBackground = new javax.swing.JPanel();
        visitorTracking_navbtn = new javax.swing.JButton();
        feedbackForum_navbtn = new javax.swing.JButton();
        paymentTracking_navbtn = new javax.swing.JButton();
        residentAccounts_navbtn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        panelContainer = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        visitorTrackingMain = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        monthlyVisitorsTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        optnVisitTrack_btn1 = new javax.swing.JButton();
        optnVisitTrack_btn2 = new javax.swing.JButton();
        optnVisitTrack_btn3 = new javax.swing.JButton();
        optnVisitTrack_btn4 = new javax.swing.JButton();
        optnVisitTrack_btn5 = new javax.swing.JButton();
        optnVisitTrack_btn6 = new javax.swing.JButton();
        optnVisitTrack_btn7 = new javax.swing.JButton();
        optnVisitTrack_btn8 = new javax.swing.JButton();
        optnVisitTrack_btn9 = new javax.swing.JButton();
        optnVisitTrack_btn10 = new javax.swing.JButton();
        optnVisitTrack_btn11 = new javax.swing.JButton();
        optnVisitTrack_btn12 = new javax.swing.JButton();
        feedbackForumMain = new javax.swing.JDesktopPane();
        newDiscussion_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        forumDiscussionsTable = new javax.swing.JTable();
        newForum = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        forumDiscTitleField = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        back_btn = new javax.swing.JButton();
        post_btn = new javax.swing.JButton();
        billPaymentTrackingMain = new javax.swing.JDesktopPane();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        jDesktopPane7 = new javax.swing.JDesktopPane();
        jDesktopPane8 = new javax.swing.JDesktopPane();

        monthlyTrack_dialog.setMaximumSize(new java.awt.Dimension(359, 158));
        monthlyTrack_dialog.setMinimumSize(new java.awt.Dimension(359, 158));
        monthlyTrack_dialog.setResizable(false);
        monthlyTrack_dialog.setLocation(200, 300);

        monthlyTrack_dialog.setLocationRelativeTo(ApartmentManagerInterface.this);
        monthlyTrack_dialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generateRpt_btn.setText("Generate report");
        generateRpt_btn.setMaximumSize(new java.awt.Dimension(144, 26));
        generateRpt_btn.setMinimumSize(new java.awt.Dimension(144, 26));
        generateRpt_btn.setPreferredSize(new java.awt.Dimension(144, 26));
        generateRpt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateRpt_btnActionPerformed(evt);
            }
        });
        monthlyTrack_dialog.getContentPane().add(generateRpt_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 48, -1, -1));

        trackedDetails_btn.setText("View tracked detaiils");
        monthlyTrack_dialog.getContentPane().add(trackedDetails_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 48, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(595, 370));
        setMinimumSize(new java.awt.Dimension(595, 370));

        appBackground.setMaximumSize(new java.awt.Dimension(595, 370));
        appBackground.setMinimumSize(new java.awt.Dimension(595, 370));
        appBackground.setPreferredSize(new java.awt.Dimension(595, 370));
        appBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visitorTracking_navbtn.setText("Visitor Tracking");
        visitorTracking_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorTracking_navbtnActionPerformed(evt);
            }
        });
        appBackground.add(visitorTracking_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 40, 130, 50));

        feedbackForum_navbtn.setText("Feedback Forum");
        feedbackForum_navbtn.setMaximumSize(new java.awt.Dimension(112, 22));
        feedbackForum_navbtn.setMinimumSize(new java.awt.Dimension(112, 22));
        feedbackForum_navbtn.setPreferredSize(new java.awt.Dimension(112, 22));
        feedbackForum_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackForum_navbtnActionPerformed(evt);
            }
        });
        appBackground.add(feedbackForum_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 100, 130, 50));

        paymentTracking_navbtn.setText("Bill Payment Tracking");
        paymentTracking_navbtn.setMargin(new java.awt.Insets(1, 5, 1, 5));
        paymentTracking_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTracking_navbtnActionPerformed(evt);
            }
        });
        appBackground.add(paymentTracking_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 160, 130, 50));

        residentAccounts_navbtn.setText("Resident Accounts");
        residentAccounts_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentAccounts_navbtnActionPerformed(evt);
            }
        });
        appBackground.add(residentAccounts_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 220, 130, 50));

        logout_btn.setText("Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        appBackground.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 335, -1, -1));

        panelContainer.setMaximumSize(new java.awt.Dimension(455, 330));
        panelContainer.setMinimumSize(new java.awt.Dimension(455, 330));
        panelContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(455, 330));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(455, 330));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(455, 330));

        visitorTrackingMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Monthly visitor tracking summary");
        visitorTrackingMain.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 21, 248, -1));

        monthlyVisitorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"January", null},
                {"February", null},
                {"March", null},
                {"April", null},
                {"May", null},
                {"June", null},
                {"July", null},
                {"August", null},
                {"September", null},
                {"October", null},
                {"November", null},
                {"December", null}
            },
            new String [] {
                "Month", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        monthlyVisitorsTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(monthlyVisitorsTable);
        monthlyVisitorsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        visitorTrackingMain.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 49, 240, 269));

        jLabel5.setText("Actions");
        visitorTrackingMain.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 56, -1, -1));

        optnVisitTrack_btn1.setText("...");
        optnVisitTrack_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optnVisitTrack_btn1ActionPerformed(evt);
            }
        });
        visitorTrackingMain.add(optnVisitTrack_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 18, 17));

        optnVisitTrack_btn2.setText("...");
        optnVisitTrack_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optnVisitTrack_btn2ActionPerformed(evt);
            }
        });
        visitorTrackingMain.add(optnVisitTrack_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 18, 17));

        optnVisitTrack_btn3.setText("...");
        optnVisitTrack_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optnVisitTrack_btn3ActionPerformed(evt);
            }
        });
        visitorTrackingMain.add(optnVisitTrack_btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 18, 17));

        optnVisitTrack_btn4.setText("...");
        optnVisitTrack_btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optnVisitTrack_btn4ActionPerformed(evt);
            }
        });
        visitorTrackingMain.add(optnVisitTrack_btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 18, 17));

        optnVisitTrack_btn5.setText("...");
        optnVisitTrack_btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optnVisitTrack_btn5ActionPerformed(evt);
            }
        });
        visitorTrackingMain.add(optnVisitTrack_btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 18, 17));

        optnVisitTrack_btn6.setText("...");
        optnVisitTrack_btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optnVisitTrack_btn6ActionPerformed(evt);
            }
        });
        visitorTrackingMain.add(optnVisitTrack_btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 18, 17));

        optnVisitTrack_btn7.setText("...");
        optnVisitTrack_btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optnVisitTrack_btn7ActionPerformed(evt);
            }
        });
        visitorTrackingMain.add(optnVisitTrack_btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 18, 17));

        optnVisitTrack_btn8.setText("...");
        optnVisitTrack_btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optnVisitTrack_btn8ActionPerformed(evt);
            }
        });
        visitorTrackingMain.add(optnVisitTrack_btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 18, 17));

        optnVisitTrack_btn9.setText("...");
        optnVisitTrack_btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optnVisitTrack_btn9ActionPerformed(evt);
            }
        });
        visitorTrackingMain.add(optnVisitTrack_btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 18, 17));

        optnVisitTrack_btn10.setText("...");
        optnVisitTrack_btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optnVisitTrack_btn10ActionPerformed(evt);
            }
        });
        visitorTrackingMain.add(optnVisitTrack_btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 18, 17));

        optnVisitTrack_btn11.setText("...");
        optnVisitTrack_btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optnVisitTrack_btn11ActionPerformed(evt);
            }
        });
        visitorTrackingMain.add(optnVisitTrack_btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 18, 17));

        optnVisitTrack_btn12.setText("...");
        optnVisitTrack_btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optnVisitTrack_btn12ActionPerformed(evt);
            }
        });
        visitorTrackingMain.add(optnVisitTrack_btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 18, 17));

        jTabbedPane1.addTab("tab1", visitorTrackingMain);

        newDiscussion_btn.setText("+ new discussion");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Discussions: Management Forum");

        forumDiscussionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(forumDiscussionsTable);

        feedbackForumMain.setLayer(newDiscussion_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        feedbackForumMain.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        feedbackForumMain.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout feedbackForumMainLayout = new javax.swing.GroupLayout(feedbackForumMain);
        feedbackForumMain.setLayout(feedbackForumMainLayout);
        feedbackForumMainLayout.setHorizontalGroup(
            feedbackForumMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedbackForumMainLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(feedbackForumMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(feedbackForumMainLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(newDiscussion_btn)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        feedbackForumMainLayout.setVerticalGroup(
            feedbackForumMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedbackForumMainLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(newDiscussion_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", feedbackForumMain);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Title");

        forumDiscTitleField.setColumns(20);
        forumDiscTitleField.setRows(5);
        jScrollPane3.setViewportView(forumDiscTitleField);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("What do you want to say?");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        back_btn.setText("< BACK");
        back_btn.setToolTipText("");

        post_btn.setText("Post");

        newForum.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        newForum.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        newForum.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        newForum.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        newForum.setLayer(back_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        newForum.setLayer(post_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout newForumLayout = new javax.swing.GroupLayout(newForum);
        newForum.setLayout(newForumLayout);
        newForumLayout.setHorizontalGroup(
            newForumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newForumLayout.createSequentialGroup()
                .addGroup(newForumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newForumLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newForumLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(newForumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(post_btn)
                            .addGroup(newForumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(back_btn)
                                .addGroup(newForumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                                    .addGroup(newForumLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane4))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        newForumLayout.setVerticalGroup(
            newForumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newForumLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(back_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(post_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", newForum);

        javax.swing.GroupLayout billPaymentTrackingMainLayout = new javax.swing.GroupLayout(billPaymentTrackingMain);
        billPaymentTrackingMain.setLayout(billPaymentTrackingMainLayout);
        billPaymentTrackingMainLayout.setHorizontalGroup(
            billPaymentTrackingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        billPaymentTrackingMainLayout.setVerticalGroup(
            billPaymentTrackingMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", billPaymentTrackingMain);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jDesktopPane5);

        javax.swing.GroupLayout jDesktopPane6Layout = new javax.swing.GroupLayout(jDesktopPane6);
        jDesktopPane6.setLayout(jDesktopPane6Layout);
        jDesktopPane6Layout.setHorizontalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        jDesktopPane6Layout.setVerticalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", jDesktopPane6);

        javax.swing.GroupLayout jDesktopPane7Layout = new javax.swing.GroupLayout(jDesktopPane7);
        jDesktopPane7.setLayout(jDesktopPane7Layout);
        jDesktopPane7Layout.setHorizontalGroup(
            jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        jDesktopPane7Layout.setVerticalGroup(
            jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab7", jDesktopPane7);

        javax.swing.GroupLayout jDesktopPane8Layout = new javax.swing.GroupLayout(jDesktopPane8);
        jDesktopPane8.setLayout(jDesktopPane8Layout);
        jDesktopPane8Layout.setHorizontalGroup(
            jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        jDesktopPane8Layout.setVerticalGroup(
            jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab8", jDesktopPane8);

        panelContainer.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, 370));

        appBackground.add(panelContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(appBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Visitor Tracking Interface
    //if uer clicks on 'Visitor Tracking', navitage to tab 1 (hidden)
    private void visitorTracking_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorTracking_navbtnActionPerformed
        
        jTabbedPane1.setSelectedIndex(0);
        
    }//GEN-LAST:event_visitorTracking_navbtnActionPerformed



    
    //if uer clicks on 'Feedback Forum', navitage to tab 2 (hidden)
    private void feedbackForum_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackForum_navbtnActionPerformed
        
        jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_feedbackForum_navbtnActionPerformed

    //if uer clicks on 'Bill Payment Tracking', navitage to tab 3 (hidden)
    private void paymentTracking_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTracking_navbtnActionPerformed
        
        jTabbedPane1.setSelectedIndex(2);
        
    }//GEN-LAST:event_paymentTracking_navbtnActionPerformed

    //if uer clicks on 'Resident Accounts', navitage to tab 4 (hidden)
    private void residentAccounts_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentAccounts_navbtnActionPerformed
        
        jTabbedPane1.setSelectedIndex(3);
        
    }//GEN-LAST:event_residentAccounts_navbtnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        //LOGOUT FUNCTION HERE
    }//GEN-LAST:event_logout_btnActionPerformed
    
    
    
    //visitor tracking option buttons
    private void optnVisitTrack_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optnVisitTrack_btn1ActionPerformed
        
        monthlyTrack_dialog.setVisible(true);
        
    }//GEN-LAST:event_optnVisitTrack_btn1ActionPerformed

    private void optnVisitTrack_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optnVisitTrack_btn2ActionPerformed
        
        monthlyTrack_dialog.setVisible(true);
        
    }//GEN-LAST:event_optnVisitTrack_btn2ActionPerformed

    private void optnVisitTrack_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optnVisitTrack_btn3ActionPerformed
        
        monthlyTrack_dialog.setVisible(true);
        
    }//GEN-LAST:event_optnVisitTrack_btn3ActionPerformed

    private void optnVisitTrack_btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optnVisitTrack_btn4ActionPerformed
        
        monthlyTrack_dialog.setVisible(true);
        
    }//GEN-LAST:event_optnVisitTrack_btn4ActionPerformed

    private void optnVisitTrack_btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optnVisitTrack_btn5ActionPerformed
        
        monthlyTrack_dialog.setVisible(true);
        
    }//GEN-LAST:event_optnVisitTrack_btn5ActionPerformed

    private void optnVisitTrack_btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optnVisitTrack_btn6ActionPerformed
        
        monthlyTrack_dialog.setVisible(true);
        
    }//GEN-LAST:event_optnVisitTrack_btn6ActionPerformed

    private void optnVisitTrack_btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optnVisitTrack_btn7ActionPerformed
        
        monthlyTrack_dialog.setVisible(true);
        
    }//GEN-LAST:event_optnVisitTrack_btn7ActionPerformed

    private void optnVisitTrack_btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optnVisitTrack_btn8ActionPerformed
        
        monthlyTrack_dialog.setVisible(true);
        
    }//GEN-LAST:event_optnVisitTrack_btn8ActionPerformed

    private void optnVisitTrack_btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optnVisitTrack_btn9ActionPerformed
        
        monthlyTrack_dialog.setVisible(true);
        
    }//GEN-LAST:event_optnVisitTrack_btn9ActionPerformed

    private void optnVisitTrack_btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optnVisitTrack_btn10ActionPerformed
        
        monthlyTrack_dialog.setVisible(true);
        
    }//GEN-LAST:event_optnVisitTrack_btn10ActionPerformed

    private void optnVisitTrack_btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optnVisitTrack_btn11ActionPerformed
        
        monthlyTrack_dialog.setVisible(true);
        
    }//GEN-LAST:event_optnVisitTrack_btn11ActionPerformed

    private void optnVisitTrack_btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optnVisitTrack_btn12ActionPerformed
        
        monthlyTrack_dialog.setVisible(true);
        
    }//GEN-LAST:event_optnVisitTrack_btn12ActionPerformed

    private void generateRpt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateRpt_btnActionPerformed
        
        monthlyTrack_dialog.setVisible(true);
        
    }//GEN-LAST:event_generateRpt_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApartmentManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApartmentManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApartmentManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApartmentManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApartmentManagerInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appBackground;
    private javax.swing.JButton back_btn;
    private javax.swing.JDesktopPane billPaymentTrackingMain;
    private javax.swing.JDesktopPane feedbackForumMain;
    private javax.swing.JButton feedbackForum_navbtn;
    private javax.swing.JTextArea forumDiscTitleField;
    private javax.swing.JTable forumDiscussionsTable;
    private javax.swing.JButton generateRpt_btn;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JDesktopPane jDesktopPane7;
    private javax.swing.JDesktopPane jDesktopPane8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JDialog monthlyTrack_dialog;
    private javax.swing.JTable monthlyVisitorsTable;
    private javax.swing.JButton newDiscussion_btn;
    private javax.swing.JDesktopPane newForum;
    private javax.swing.JButton optnVisitTrack_btn1;
    private javax.swing.JButton optnVisitTrack_btn10;
    private javax.swing.JButton optnVisitTrack_btn11;
    private javax.swing.JButton optnVisitTrack_btn12;
    private javax.swing.JButton optnVisitTrack_btn2;
    private javax.swing.JButton optnVisitTrack_btn3;
    private javax.swing.JButton optnVisitTrack_btn4;
    private javax.swing.JButton optnVisitTrack_btn5;
    private javax.swing.JButton optnVisitTrack_btn6;
    private javax.swing.JButton optnVisitTrack_btn7;
    private javax.swing.JButton optnVisitTrack_btn8;
    private javax.swing.JButton optnVisitTrack_btn9;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JButton paymentTracking_navbtn;
    private javax.swing.JButton post_btn;
    private javax.swing.JButton residentAccounts_navbtn;
    private javax.swing.JButton trackedDetails_btn;
    private javax.swing.JDesktopPane visitorTrackingMain;
    private javax.swing.JButton visitorTracking_navbtn;
    // End of variables declaration//GEN-END:variables
}
