/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg5009cem_assignment;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sjjde
 */
public class MFeedbackForumMain extends javax.swing.JFrame {

    /**
     * Creates new form FeedbackForumMain
     */
    public MFeedbackForumMain() {
        initComponents();
        displayDiscussions();
    }
    
    //variable declaration
    private String username;
    
    public MFeedbackForumMain(String username){
       initComponents();
       this.username = username;
       
       displayDiscussions();
    }
    
    
    //close entire UI window when navbtn clicked
    public void close() {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        newDis_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mForumDis_table = new javax.swing.JTable();
        visitorTrack_navbtn = new javax.swing.JButton();
        forum_navbtn = new javax.swing.JButton();
        paymentTrack_navbtn = new javax.swing.JButton();
        residentAcc_navbtn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(595, 370));
        setMinimumSize(new java.awt.Dimension(595, 370));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(857, 497));
        jPanel1.setMinimumSize(new java.awt.Dimension(857, 497));
        jPanel1.setPreferredSize(new java.awt.Dimension(857, 497));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(720, 460));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(720, 460));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newDis_btn.setText("+ new discussion");
        newDis_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDis_btnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(newDis_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Discussions: Management Forum");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        mForumDis_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Discussions"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        //making the table row clickable
        mForumDis_table.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(!e.getValueIsAdjusting()) {
                    int selected = mForumDis_table.getSelectedRow();

                    if (selected != -1) {
                        String discussion = (String) mForumDis_table.getValueAt(selected,0);

                        close();
                        MOngoingDis pi = new MOngoingDis(discussion, username);
                        pi.setTitle(discussion);
                        pi.setLocationRelativeTo(null); //center the form
                        pi.setVisible(true);
                    }
                }
            }
        });
        jScrollPane1.setViewportView(mForumDis_table);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 680, 340));

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 720, 460));

        visitorTrack_navbtn.setText("Visitor Tracking");
        visitorTrack_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorTrack_navbtnActionPerformed(evt);
            }
        });
        jPanel1.add(visitorTrack_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, -1));

        forum_navbtn.setText("Feedback Forum");
        jPanel1.add(forum_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, -1));

        paymentTrack_navbtn.setText("Bill Payment Tracking");
        paymentTrack_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTrack_navbtnActionPerformed(evt);
            }
        });
        jPanel1.add(paymentTrack_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 130, -1));

        residentAcc_navbtn.setText("Resident Accounts");
        residentAcc_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentAcc_navbtnActionPerformed(evt);
            }
        });
        jPanel1.add(residentAcc_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 130, -1));

        logout_btn.setText("Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        jPanel1.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel2.setText("Feedback Forum");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //when user clicks on the button to navigate to 'Visitor Tracking'
    private void visitorTrack_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorTrack_navbtnActionPerformed
        
        close();
        MVisitorTrackingMain pi = new MVisitorTrackingMain(username);
        pi.setTitle("Visitor Tracking");
        pi.setLocationRelativeTo(null); //center the form
        pi.setVisible(true);
        
    }//GEN-LAST:event_visitorTrack_navbtnActionPerformed

    //when user clicks on the button to navigate to 'Bill Payment Tracking'
    private void paymentTrack_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTrack_navbtnActionPerformed
    
        close();
        MBillPayTrackingMain pi = new MBillPayTrackingMain(username);
        pi.setTitle("Bill Payment Tracking");
        pi.setLocationRelativeTo(null); //center the form
        pi.setVisible(true);
        
    }//GEN-LAST:event_paymentTrack_navbtnActionPerformed

    //when user clicks on the button to navigate to 'Resident Accounts'
    private void residentAcc_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentAcc_navbtnActionPerformed
    
        close();
        MResidentAccountsMain pi = new MResidentAccountsMain(username);
        pi.setTitle("Resident Accounts");
        pi.setLocationRelativeTo(null); //center the form
        pi.setVisible(true);
        
    }//GEN-LAST:event_residentAcc_navbtnActionPerformed

    //when user clicks on the 'logout' button
    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
    
        int res = JOptionPane.showConfirmDialog(logout_btn, "Are you sure you want to sign out?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (res == JOptionPane.YES_OPTION) {
                dispose();
                MainLogin login = new MainLogin();
                login.setTitle("Main Login Page");
                login.setLocationRelativeTo(null); //center the form
                login.setVisible(true);
            }
            else {
                dispose();
                MFeedbackForumMain pi = new MFeedbackForumMain(username);
                pi.setTitle("Resident Accounts");
                pi.setLocationRelativeTo(null); //center the form
                pi.setVisible(true);
            }
        
    }//GEN-LAST:event_logout_btnActionPerformed

    
    //when user clicks on '+ new discussion' to open the new discussion page
    private void newDis_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDis_btnActionPerformed
        
        close();
        MNewDis pi = new MNewDis(username);
        pi.setTitle("New management forum discussion");
        pi.setLocationRelativeTo(null); //center the form
        pi.setVisible(true);
        
    }//GEN-LAST:event_newDis_btnActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MFeedbackForumMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MFeedbackForumMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MFeedbackForumMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MFeedbackForumMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MFeedbackForumMain().setVisible(true);
            }
        });
    }
    
    
    
    //sini sini
    
    
    
    //display discussions
    private void displayDiscussions() {
        
        Connection conn = ConnectDB.connectDB();
        if (conn != null) {
            try {
                //Statement st = conn.createStatement();
                PreparedStatement pst = (PreparedStatement) conn.prepareStatement("SELECT * FROM manager_forum");
                //pst.setString(1, "title"); //telling the system to query for data inside "title"
                
                ResultSet rs = pst.executeQuery();
                
                DefaultTableModel model = (DefaultTableModel) mForumDis_table.getModel();
                model.setRowCount(0);
                
                while (rs.next()) {
                    
                    String disTitle = rs.getString("title");

                    //add data to the table
                    model.addRow(new Object[]{disTitle});
 
                }
                rs.close();
                pst.close();
                conn.close();
            } catch (SQLException ex) {
                 Logger.getLogger(MFeedbackForumMain.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton forum_navbtn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JTable mForumDis_table;
    private javax.swing.JButton newDis_btn;
    private javax.swing.JButton paymentTrack_navbtn;
    private javax.swing.JButton residentAcc_navbtn;
    private javax.swing.JButton visitorTrack_navbtn;
    // End of variables declaration//GEN-END:variables
}
