/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg5009cem_assignment;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sjjde
 */
public class MOngoingDis extends javax.swing.JFrame {

    /**
     * Creates new form MOngoingDis
     */
    public MOngoingDis() {
        initComponents();
        displayThread(discussion);
    }
    
    //variable declaration
    private String discussion;
    private String username;
    
    MOngoingDis(String discussion, String username) {
        initComponents();
        this.discussion = discussion;
        this.username = username;
        displayThread(discussion);
    }
    
    //close entire UI window when navbtn is clicked
    public void close() {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        fUser_display = new javax.swing.JLabel();
        fTitle_display = new javax.swing.JLabel();
        fContent_display = new javax.swing.JLabel();
        addComment_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        visitorTrack_navbtn = new javax.swing.JButton();
        paymentTrack_navbtn = new javax.swing.JButton();
        residentAcc_navbtn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        forum_navbtn = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(857, 497, 497, 497));
        setMaximumSize(new java.awt.Dimension(857, 497));
        setMinimumSize(new java.awt.Dimension(857, 497));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(857, 497));
        jPanel1.setMinimumSize(new java.awt.Dimension(857, 497));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(720, 460));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(720, 460));

        fUser_display.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        fUser_display.setText("jLabel2");

        fTitle_display.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        fTitle_display.setText("jLabel2");

        fContent_display.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fContent_display.setText("jLabel2");
        fContent_display.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fContent_display, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fUser_display, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fTitle_display, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(fUser_display)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fTitle_display)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fContent_display, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        addComment_btn.setText("Add comment");

        back_btn.setText("<BACK");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(addComment_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(back_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back_btn)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addComment_btn)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(back_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addComment_btn)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel3.setText("Ongoing discussion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        visitorTrack_navbtn.setText("Visitor Tracking");
        visitorTrack_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorTrack_navbtnActionPerformed(evt);
            }
        });
        jPanel1.add(visitorTrack_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, -1));

        paymentTrack_navbtn.setText("Bill Payment Tracking");
        paymentTrack_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTrack_navbtnActionPerformed(evt);
            }
        });
        jPanel1.add(paymentTrack_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 130, -1));

        residentAcc_navbtn.setText("Resident Accounts");
        residentAcc_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentAcc_navbtnActionPerformed(evt);
            }
        });
        jPanel1.add(residentAcc_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 130, -1));

        logout_btn.setText("Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        jPanel1.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        forum_navbtn.setText("Feedback Forum");
        jPanel1.add(forum_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //when user clicks on the button to navigate to 'Bill Payment Tracking'
    private void paymentTrack_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTrack_navbtnActionPerformed

        close();
        MBillPayTrackingMain pi = new MBillPayTrackingMain(username);
        pi.setTitle("Bill Payment Tracking");
        pi.setLocationRelativeTo(null); //center the form
        pi.setVisible(true);

    }//GEN-LAST:event_paymentTrack_navbtnActionPerformed

    //when user clicks on the button to navigate to 'Resident Accounts'
    private void residentAcc_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentAcc_navbtnActionPerformed

        close();
        MResidentAccountsMain pi = new MResidentAccountsMain(username);
        pi.setTitle("Resident Accounts");
        pi.setLocationRelativeTo(null); //center the form
        pi.setVisible(true);

    }//GEN-LAST:event_residentAcc_navbtnActionPerformed

    //when user clicks on 'logout' button
    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed

        int res = JOptionPane.showConfirmDialog(logout_btn, "Are you sure you want to sign out?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (res == JOptionPane.YES_OPTION) {
            dispose();
            MainLogin login = new MainLogin();
            login.setTitle("Main Login Page");
            login.setLocationRelativeTo(null); //center the form
            login.setVisible(true);
        }
        else {
            dispose();
            MOngoingDis pi = new MOngoingDis(discussion, username);
            pi.setTitle("Resident Accounts");
            pi.setLocationRelativeTo(null); //center the form
            pi.setVisible(true);
        }

    }//GEN-LAST:event_logout_btnActionPerformed

    //when user clicks on the button to navigate to 'Visitor Tracking'
    private void visitorTrack_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorTrack_navbtnActionPerformed
        
        close();
        MVisitorTrackingMain pi = new MVisitorTrackingMain(username);
        pi.setVisible(true);
        
    }//GEN-LAST:event_visitorTrack_navbtnActionPerformed

    //when user clicks on 'BACK' button
    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        
        close();
        MFeedbackForumMain pi = new MFeedbackForumMain(username);
        pi.setTitle("Feedback Forum");
        pi.setLocationRelativeTo(null); //center the form
        pi.setVisible(true);
        
    }//GEN-LAST:event_back_btnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MOngoingDis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MOngoingDis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MOngoingDis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MOngoingDis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MOngoingDis().setVisible(true);
            }
        });
    }
    
    
    //display ongoing discussion
    private void displayThread(String discussion) {
        
        Connection conn = ConnectDB.connectDB();
        if (conn != null) {
        try {
            String query = "SELECT title,text,user FROM manager_forum WHERE title = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, discussion);
            
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
            String user = rs.getString("user");
            String title = rs.getString("title");
            String content = rs.getString("text");


            //Displaying the discussion
            fUser_display.setText(user);
            fTitle_display.setText(title);
            fContent_display.setText(content);
        }
        rs.close();
        pst.close();
        conn.close();
            
        }   catch (SQLException ex) {
                Logger.getLogger(MOngoingDis.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComment_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel fContent_display;
    private javax.swing.JLabel fTitle_display;
    private javax.swing.JLabel fUser_display;
    private javax.swing.JButton forum_navbtn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton paymentTrack_navbtn;
    private javax.swing.JButton residentAcc_navbtn;
    private javax.swing.JButton visitorTrack_navbtn;
    // End of variables declaration//GEN-END:variables
}
