/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg5009cem_assignment;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sjjde
 */
public class MResidentAccountsMain extends javax.swing.JFrame {

    /**
     * Creates new form ResidentAccountsMain
     */
    public MResidentAccountsMain() {
        initComponents();
        displayAllResidents();
    }
    
    
    //close entire UI window when navbtn clicked
    public void close(){
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        createNewAcc_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allResidents_table = new javax.swing.JTable();
        visitorTrack_navbtn = new javax.swing.JButton();
        forum_navbtn = new javax.swing.JButton();
        paymentTrack_navbtn = new javax.swing.JButton();
        residentAcc_navbtn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(857, 497));
        setMinimumSize(new java.awt.Dimension(857, 497));
        setPreferredSize(new java.awt.Dimension(857, 497));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(857, 497));
        jPanel2.setMinimumSize(new java.awt.Dimension(857, 497));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 0, -1, -1));

        jDesktopPane2.setMaximumSize(new java.awt.Dimension(720, 460));
        jDesktopPane2.setMinimumSize(new java.awt.Dimension(720, 460));

        createNewAcc_btn.setText("+ new accounts");
        createNewAcc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewAcc_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Resident accounts");

        allResidents_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account ID", "Resident name", "Car plate no.", "Phone no.", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(allResidents_table);

        jDesktopPane2.setLayer(createNewAcc_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createNewAcc_btn)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(createNewAcc_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 37, -1, -1));

        visitorTrack_navbtn.setText("Visitor Tracking");
        visitorTrack_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorTrack_navbtnActionPerformed(evt);
            }
        });
        getContentPane().add(visitorTrack_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 131, -1));

        forum_navbtn.setText("Feedback Forum");
        forum_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forum_navbtnActionPerformed(evt);
            }
        });
        getContentPane().add(forum_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 131, -1));

        paymentTrack_navbtn.setText("Bill Payment Tracking");
        paymentTrack_navbtn.setPreferredSize(new java.awt.Dimension(121, 26));
        paymentTrack_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTrack_navbtnActionPerformed(evt);
            }
        });
        getContentPane().add(paymentTrack_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 131, -1));

        residentAcc_navbtn.setText("Resident Accounts");
        getContentPane().add(residentAcc_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 130, -1));

        logout_btn.setText("Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        getContentPane().add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jLabel1.setText("Resident Accounts");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //when user clicks on the button to navigate to 'Visitor Tracking'
    private void visitorTrack_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorTrack_navbtnActionPerformed
        
        close();
        MVisitorTrackingMain pi = new MVisitorTrackingMain();
        pi.setTitle("Visitor Tracking");
        pi.setLocationRelativeTo(null);
        pi.setVisible(true);
        
    }//GEN-LAST:event_visitorTrack_navbtnActionPerformed

    //when user clicks on the button to navigate to 'Feedback Forum'
    private void forum_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forum_navbtnActionPerformed
        
        close();
        MFeedbackForumMain pi = new MFeedbackForumMain();
        pi.setTitle("Feedback Forum");
        pi.setLocationRelativeTo(null);
        pi.setVisible(true);
        
    }//GEN-LAST:event_forum_navbtnActionPerformed

    //when user clicks on the button to navigate to 'Bill Payment Tracking'
    private void paymentTrack_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTrack_navbtnActionPerformed
        
        close();
        MBillPayTrackingMain pi = new MBillPayTrackingMain();
        pi.setTitle("Bill Payment Tracking");
        pi.setLocationRelativeTo(null);
        pi.setVisible(true);
        
    }//GEN-LAST:event_paymentTrack_navbtnActionPerformed

    //when user clicks on the 'logout' button
    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
    
        int res = JOptionPane.showConfirmDialog(logout_btn, "Are you sure you want to sign out?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (res == JOptionPane.YES_OPTION) {
                dispose();
                MainLogin login = new MainLogin();
                login.setTitle("Main Login Page");
                login.setLocationRelativeTo(null); //center the form
                login.setVisible(true);
            }
            else {
                dispose();
                MResidentAccountsMain pi = new MResidentAccountsMain();
                pi.setTitle("Resident Accounts");
                pi.setLocationRelativeTo(null); //center the form
                pi.setVisible(true);
            }
        
    }//GEN-LAST:event_logout_btnActionPerformed

    private void createNewAcc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewAcc_btnActionPerformed
        
        close();
        MCreateNewResident pi = new MCreateNewResident();
        pi.setTitle("Resident Accounts - Create new resident accounts");
        pi.setLocationRelativeTo(null); //center the form
        pi.setVisible(true);
        
    }//GEN-LAST:event_createNewAcc_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MResidentAccountsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MResidentAccountsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MResidentAccountsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MResidentAccountsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MResidentAccountsMain().setVisible(true);
            }
        });
    }
    
    
    private void displayAllResidents() {
        
        Connection conn = (Connection) ConnectDB.connectDB();
        if (conn != null) {
            try {
                //Statement st = conn.createStatement();
                PreparedStatement pst = (PreparedStatement) conn.prepareStatement("SELECT * FROM resident");
                //pst.setString(1, "title"); //telling the system to query for data inside "title"
                
                ResultSet rs = pst.executeQuery();
                
                DefaultTableModel allResTableModel = (DefaultTableModel) allResidents_table.getModel();
                allResTableModel.setRowCount(0);
                while (rs.next()) {
                    
                    String accID = rs.getString("unit_number");
                    String pass = rs.getString("password");
                    String rName = rs.getString("resident_name");
                    String email = rs.getString("email");
                    String phoneNo = rs.getString("telefon_number");
                    String carPlate = rs.getString("car_plate_no");
                    
                    //String[] resRowData = {accID, pass, rName, email, phoneNo, carPlate};
                    
                    //mForumDis_table.setModel(disTableModel);

                    allResTableModel.addRow(new Object[]{accID, pass, rName, email, phoneNo, carPlate});
                    
                    
                }
                rs.close();
                pst.close();
                conn.close();
            } catch (SQLException ex) {
                 Logger.getLogger(RD.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable allResidents_table;
    private javax.swing.JButton createNewAcc_btn;
    private javax.swing.JButton forum_navbtn;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton paymentTrack_navbtn;
    private javax.swing.JButton residentAcc_navbtn;
    private javax.swing.JButton visitorTrack_navbtn;
    // End of variables declaration//GEN-END:variables
}
