/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg5009cem_assignment;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sjjde
 */
public class MVisitorTrackingMain extends javax.swing.JFrame {

    /**
     * Creates new form visitorTrackingMain
     */
    public MVisitorTrackingMain() {
        initComponents();
    }
    
    //variable declaration
    private String month;
    
    //close entire UI page when navbtn clicked
    public void close() {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visitorTrack_table = new javax.swing.JTable();
        trackedVisitorsJan_btn = new javax.swing.JButton();
        trackedVisitorsFeb_btn = new javax.swing.JButton();
        trackedVisitorsMar_btn = new javax.swing.JButton();
        trackedVisitorsApr_btn = new javax.swing.JButton();
        trackedVisitorsMay_btn = new javax.swing.JButton();
        trackedVisitorsJun_btn = new javax.swing.JButton();
        trackedVisitorsJul_btn = new javax.swing.JButton();
        trackedVisitorsAug_btn = new javax.swing.JButton();
        trackedVisitorsSep_btn = new javax.swing.JButton();
        trackedVisitorsOct_btn = new javax.swing.JButton();
        trackedVisitorsNov_btn = new javax.swing.JButton();
        trackedVisitorsDec_btn = new javax.swing.JButton();
        visitorTrack_navbtn = new javax.swing.JButton();
        forum_navbtn = new javax.swing.JButton();
        paymentTrack_navbtn = new javax.swing.JButton();
        residentAcc_navbtn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(857, 497));
        setMinimumSize(new java.awt.Dimension(857, 497));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(832, 471));
        jPanel1.setMinimumSize(new java.awt.Dimension(857, 497));
        jPanel1.setPreferredSize(new java.awt.Dimension(857, 497));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(720, 460));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(720, 460));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Monthly Visitor Tracking");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 21, 200, 20));

        visitorTrack_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Car plate no.", "Reason for visit", "Date", "Time in", "Time out"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(visitorTrack_table);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 570, 360));

        trackedVisitorsJan_btn.setText("January");
        trackedVisitorsJan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackedVisitorsJan_btnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(trackedVisitorsJan_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, -1));

        trackedVisitorsFeb_btn.setText("February");
        trackedVisitorsFeb_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackedVisitorsFeb_btnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(trackedVisitorsFeb_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, -1));

        trackedVisitorsMar_btn.setText("March");
        trackedVisitorsMar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackedVisitorsMar_btnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(trackedVisitorsMar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, -1));

        trackedVisitorsApr_btn.setText("April");
        trackedVisitorsApr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackedVisitorsApr_btnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(trackedVisitorsApr_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, -1));

        trackedVisitorsMay_btn.setText("May");
        trackedVisitorsMay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackedVisitorsMay_btnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(trackedVisitorsMay_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, -1));

        trackedVisitorsJun_btn.setText("June");
        trackedVisitorsJun_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackedVisitorsJun_btnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(trackedVisitorsJun_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, -1));

        trackedVisitorsJul_btn.setText("July");
        trackedVisitorsJul_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackedVisitorsJul_btnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(trackedVisitorsJul_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 90, -1));

        trackedVisitorsAug_btn.setText("August");
        trackedVisitorsAug_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackedVisitorsAug_btnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(trackedVisitorsAug_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, -1));

        trackedVisitorsSep_btn.setText("September");
        trackedVisitorsSep_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackedVisitorsSep_btnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(trackedVisitorsSep_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, -1));

        trackedVisitorsOct_btn.setText("October");
        trackedVisitorsOct_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackedVisitorsOct_btnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(trackedVisitorsOct_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, -1));

        trackedVisitorsNov_btn.setText("November");
        trackedVisitorsNov_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackedVisitorsNov_btnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(trackedVisitorsNov_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 90, -1));

        trackedVisitorsDec_btn.setText("December");
        trackedVisitorsDec_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackedVisitorsDec_btnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(trackedVisitorsDec_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 90, -1));

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 720, 460));

        visitorTrack_navbtn.setText("Visitor Tracking");
        jPanel1.add(visitorTrack_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, -1));

        forum_navbtn.setText("Feedback Forum");
        forum_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forum_navbtnActionPerformed(evt);
            }
        });
        jPanel1.add(forum_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, -1));

        paymentTrack_navbtn.setText("Bill Payment Tracking");
        paymentTrack_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTrack_navbtnActionPerformed(evt);
            }
        });
        jPanel1.add(paymentTrack_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 130, -1));

        residentAcc_navbtn.setText("Resident Accounts");
        residentAcc_navbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentAcc_navbtnActionPerformed(evt);
            }
        });
        jPanel1.add(residentAcc_navbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 130, -1));

        logout_btn.setText("Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        jPanel1.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jLabel3.setText("Visitor Tracking");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //when user clicks on the button to navigate to 'Feedback Forum'
    private void forum_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forum_navbtnActionPerformed
        
        close();
        MFeedbackForumMain pi = new MFeedbackForumMain();
        pi.setTitle("Feedback Forum");
        pi.setLocationRelativeTo(null); //center the form
        pi.setVisible(true);
        
    }//GEN-LAST:event_forum_navbtnActionPerformed

    //when user clicks on the button to navigate to 'Bill Payment Tracking'
    private void paymentTrack_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTrack_navbtnActionPerformed
        
        close();
        MBillPayTrackingMain pi = new MBillPayTrackingMain();
        pi.setTitle("Bill Payment Tracking");
        pi.setLocationRelativeTo(null); //center the form
        pi.setVisible(true);
        
    }//GEN-LAST:event_paymentTrack_navbtnActionPerformed

    //when user clicks on the button to navigate to 'Resident Accounts'
    private void residentAcc_navbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentAcc_navbtnActionPerformed
        
        close();
        MResidentAccountsMain pi = new MResidentAccountsMain();
        pi.setTitle("Resident Accounts");
        pi.setLocationRelativeTo(null); //center the form
        pi.setVisible(true);
        
    }//GEN-LAST:event_residentAcc_navbtnActionPerformed

    //when user clicks on the 'logout' button
    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
    
        int res = JOptionPane.showConfirmDialog(logout_btn, "Are you sure you want to sign out?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (res == JOptionPane.YES_OPTION) {
                dispose();
                MainLogin login = new MainLogin();
                login.setTitle("Main Login Page");
                login.setLocationRelativeTo(null); //center the form
                login.setVisible(true);
            }
            else {
                dispose();
                MVisitorTrackingMain pi = new MVisitorTrackingMain();
                pi.setTitle("Resident Accounts");
                pi.setLocationRelativeTo(null); //center the form
                pi.setVisible(true);
            }
        
    }//GEN-LAST:event_logout_btnActionPerformed

    
    //when user views January's records
    private void trackedVisitorsJan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackedVisitorsJan_btnActionPerformed
        
        month = "January";
        getVisitors(month);
        
    }//GEN-LAST:event_trackedVisitorsJan_btnActionPerformed

    //when user views February's records
    private void trackedVisitorsFeb_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackedVisitorsFeb_btnActionPerformed
        
        month = "February";
        getVisitors(month);
        
    }//GEN-LAST:event_trackedVisitorsFeb_btnActionPerformed

    //when user views March's records
    private void trackedVisitorsMar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackedVisitorsMar_btnActionPerformed
        
        month = "March";
        getVisitors(month);
        
    }//GEN-LAST:event_trackedVisitorsMar_btnActionPerformed

    //when user views April's records
    private void trackedVisitorsApr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackedVisitorsApr_btnActionPerformed
        
        month = "April";
        getVisitors(month);
        
    }//GEN-LAST:event_trackedVisitorsApr_btnActionPerformed

    //when user views May's records
    private void trackedVisitorsMay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackedVisitorsMay_btnActionPerformed
        
        month = "May";
        getVisitors(month);
        
    }//GEN-LAST:event_trackedVisitorsMay_btnActionPerformed

    //when user views June's records
    private void trackedVisitorsJun_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackedVisitorsJun_btnActionPerformed
        
        month = "June";
        getVisitors(month);
        
    }//GEN-LAST:event_trackedVisitorsJun_btnActionPerformed

    //when user views July's records
    private void trackedVisitorsJul_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackedVisitorsJul_btnActionPerformed
        
        month = "July";
        getVisitors(month);
        
    }//GEN-LAST:event_trackedVisitorsJul_btnActionPerformed

    //when user views August's records
    private void trackedVisitorsAug_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackedVisitorsAug_btnActionPerformed
        
        month = "August";
        getVisitors(month);
        
    }//GEN-LAST:event_trackedVisitorsAug_btnActionPerformed

    //when user views September's records
    private void trackedVisitorsSep_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackedVisitorsSep_btnActionPerformed
        
        month = "September";
        getVisitors(month);
        
    }//GEN-LAST:event_trackedVisitorsSep_btnActionPerformed

    //when user views October's records
    private void trackedVisitorsOct_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackedVisitorsOct_btnActionPerformed
        
        month = "October";
        getVisitors(month);
        
    }//GEN-LAST:event_trackedVisitorsOct_btnActionPerformed

    //when user views November's records
    private void trackedVisitorsNov_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackedVisitorsNov_btnActionPerformed
        
        month = "November";
        getVisitors(month);
        
    }//GEN-LAST:event_trackedVisitorsNov_btnActionPerformed

    //when user views December's records
    private void trackedVisitorsDec_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackedVisitorsDec_btnActionPerformed
        
        month = "December";
        getVisitors(month);
        
    }//GEN-LAST:event_trackedVisitorsDec_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MVisitorTrackingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MVisitorTrackingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MVisitorTrackingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MVisitorTrackingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MVisitorTrackingMain().setVisible(true);
            }
        });
    }
    
    
    
    //pulling visitor info from database
    private void getVisitors(String month) {
        Connection conn = (Connection) ConnectDB.connectDB();
        if (conn != null) {
            try {
                //Statement st = conn.createStatement();
                PreparedStatement pst = (PreparedStatement) conn.prepareStatement("SELECT * FROM visitor WHERE month = ?");
                pst.setString(1, month);
                
                ResultSet rs = pst.executeQuery();
                
                DefaultTableModel model = (DefaultTableModel) visitorTrack_table.getModel();
                model.setRowCount(0);
                while (rs.next()) {
                    
                    String vName = rs.getString("name");
                    String carPlate = rs.getString("car_plate_no");
                    String reasonVisit = rs.getString("reason_visit");
                    String date = rs.getString("date");
                    String timeI = rs.getString("time_in");
                    String timeO = rs.getString("time_out");

                    model.addRow(new Object[]{vName, carPlate, reasonVisit, date, timeI, timeO});
                    
                    
                }
                rs.close();
                pst.close();
                conn.close();
            } catch (SQLException ex) {
                 Logger.getLogger(RD.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton forum_navbtn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton paymentTrack_navbtn;
    private javax.swing.JButton residentAcc_navbtn;
    private javax.swing.JButton trackedVisitorsApr_btn;
    private javax.swing.JButton trackedVisitorsAug_btn;
    private javax.swing.JButton trackedVisitorsDec_btn;
    private javax.swing.JButton trackedVisitorsFeb_btn;
    private javax.swing.JButton trackedVisitorsJan_btn;
    private javax.swing.JButton trackedVisitorsJul_btn;
    private javax.swing.JButton trackedVisitorsJun_btn;
    private javax.swing.JButton trackedVisitorsMar_btn;
    private javax.swing.JButton trackedVisitorsMay_btn;
    private javax.swing.JButton trackedVisitorsNov_btn;
    private javax.swing.JButton trackedVisitorsOct_btn;
    private javax.swing.JButton trackedVisitorsSep_btn;
    private javax.swing.JButton visitorTrack_navbtn;
    private javax.swing.JTable visitorTrack_table;
    // End of variables declaration//GEN-END:variables
}
